### ISSUE TITLE
Support actually running tests and feeding back results

### ISSUE THREAD

**Issue by pistachiomatt** [di-sukharev/AI-TDD#4]
For non-trivial / implementations where they could be interpreted in many different ways, GPT4 will still miss in a zero-shot attempt. Perhaps you could run the test file and feed the results into a second execution of `aitdd`. Recursive AI coding—the dream!

**Comment by di-sukharev** [comment]
wow, that's is smart — anybody wants to make the PR? if no — this is the next thing i'm playing with!
